apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-k8s-api
  name: test-k8s-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-k8s-api
  template:
    metadata:
      labels:
        app: test-k8s-api
    spec:
      containers:
      - image: # TODO: registry link
        name: test-k8s-api
        ports:
          - containerPort: 5001
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: test-k8s-api
  ports:
    - port: 5001
      targetPort: 5001
  type: NodePort
