name: Build new image version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        source .env 
        docker buildx build  --file Dockerfile --platform "$DOCKER_PLATFORM" . -t $DOCKER_USER_NAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG --push
